name: Bot server deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, meichu-u20]
    steps:
      - uses: actions/checkout@v4
      - name: Deploy app files
        run: |
          rsync --recursive --delete --exclude '.git' ./ /app/wordwhale-webhook/
