name: Bot server deployment

on:
  push:
    branches:
      - main
      # ci test
      - ci-chou-test-*
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: List path and contents
        run: |
          pwd
          ls -alFR .
      # - name: Restart app.py
      #   run: |
      #     python -m app.py
